# Sample HN-TUI configuration. Copy to:
#   Windows: %APPDATA%/hn-tui/config.yaml
#   macOS/Linux: $XDG_CONFIG_HOME/hn-tui/config.yaml (defaults to ~/.config/hn-tui/config.yaml)
#
# Note: HN-TUI uses the public Hacker News API and requires no authentication.
# The reddit section is kept for compatibility but not used.
reddit:
  client_id: ""
  client_secret: ""
  user_agent: "hn-tui/0.1 (+https://github.com/danielmerja/hn-tui)"
  scopes: []
  redirect_uri: "http://127.0.0.1:65010/hn-tui/callback"
ui:
  theme: default
media:
  cache_dir: null
  max_size_bytes: 524288000
  default_ttl: "6h"
  workers: 2
player:
  video_command:
    - mpv
    - --fs
    - "%URL%"
  video_detach: true
